"""
Response Models

Models for suggested responses and response templates.
"""

from datetime import datetime
from typing import Optional, List
from enum import Enum

from sqlalchemy import (
    Column, String, Integer, Float, Text, DateTime,
    Boolean, JSON, Enum as SQLEnum, ForeignKey
)
from sqlalchemy.dialects.postgresql import UUID
import uuid

from src.database import Base


class TemplateType(str, Enum):
    """Types of response templates."""
    GREETING = "greeting"
    CLOSING = "closing"
    ACKNOWLEDGMENT = "acknowledgment"
    SOLUTION = "solution"
    ESCALATION = "escalation"
    FOLLOW_UP = "follow_up"
    AUTO_REPLY = "auto_reply"
    FAQ = "faq"


class ResponseTemplate(Base):
    """
    Pre-defined response templates.
    
    Templates can be used for auto-replies, suggested responses,
    or as building blocks for agent responses.
    
    Attributes:
        id: Unique template identifier
        name: Template name/title
        content: Template content with optional placeholders
        content_tr: Turkish version of content
        
        # Classification
        template_type: Type of template
        categories: Categories this template applies to
        
        # Usage
        is_active: Whether template is active
        usage_count: How many times used
    """
    
    __tablename__ = "response_templates"
    
    # Primary key
    id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        index=True
    )
    
    # Basic info
    name = Column(String(200), nullable=False)
    description = Column(Text, nullable=True)
    
    # Content
    content = Column(Text, nullable=False)
    content_tr = Column(Text, nullable=True)  # Turkish version
    
    # Subject (for email templates)
    subject = Column(String(500), nullable=True)
    subject_tr = Column(String(500), nullable=True)
    
    # Classification
    template_type = Column(
        SQLEnum(TemplateType),
        nullable=False,
        index=True
    )
    
    # Applicable categories (stored as JSON for SQLite compatibility)
    categories = Column(JSON, default=list)
    
    # Placeholders available in this template
    # e.g., ["customer_name", "ticket_id", "agent_name"]
    placeholders = Column(JSON, default=list)
    
    # Tags for search/filter
    tags = Column(JSON, default=list)
    
    # Status
    is_active = Column(Boolean, default=True, index=True)
    is_public = Column(Boolean, default=True)  # Visible to all agents
    
    # Usage statistics
    usage_count = Column(Integer, default=0)
    last_used_at = Column(DateTime(timezone=True), nullable=True)
    avg_rating = Column(Float, nullable=True)  # Agent rating of template
    
    # Ownership
    created_by = Column(String(255), nullable=True)
    team = Column(String(100), nullable=True)
    
    # Extra data
    extra_data = Column(JSON, default=dict)
    
    # Timestamps
    created_at = Column(
        DateTime(timezone=True),
        default=datetime.utcnow,
        nullable=False
    )
    updated_at = Column(
        DateTime(timezone=True),
        default=datetime.utcnow,
        onupdate=datetime.utcnow,
        nullable=False
    )
    
    def __repr__(self) -> str:
        return f"<ResponseTemplate(name={self.name}, type={self.template_type})>"
    
    def get_content(self, language: str = "en") -> str:
        """Get content in specified language."""
        if language == "tr" and self.content_tr:
            return self.content_tr
        return self.content
    
    def render(self, context: dict, language: str = "en") -> str:
        """
        Render template with context values.
        
        Args:
            context: Dictionary of placeholder values
            language: Language to render in
            
        Returns:
            str: Rendered template content
        """
        content = self.get_content(language)
        
        for placeholder in self.placeholders:
            value = context.get(placeholder, f"[{placeholder}]")
            content = content.replace(f"{{{placeholder}}}", str(value))
        
        return content


class SuggestedResponse(Base):
    """
    AI-suggested response for a specific ticket.
    
    These are generated by the RAG system based on similar past tickets
    and the knowledge base.
    
    Attributes:
        id: Unique suggestion identifier
        ticket_id: Associated ticket
        content: Suggested response content
        
        # Source
        source_type: Where suggestion came from (rag, template, ai)
        source_id: ID of source (template_id, knowledge_base_doc_id, etc.)
        
        # Quality
        relevance_score: How relevant to the ticket (0-1)
        confidence: Confidence in suggestion (0-1)
        
        # Feedback
        was_used: Whether agent used this suggestion
        rating: Agent rating of suggestion
    """
    
    __tablename__ = "suggested_responses"
    
    # Primary key
    id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        index=True
    )
    
    # Associated ticket
    ticket_id = Column(
        UUID(as_uuid=True),
        ForeignKey("tickets.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    
    # Content
    content = Column(Text, nullable=False)
    content_html = Column(Text, nullable=True)  # HTML formatted version
    summary = Column(String(500), nullable=True)  # Brief summary
    
    # Source information
    source_type = Column(String(50), nullable=False)  # rag, template, ai_generated
    source_id = Column(String(255), nullable=True)  # Template ID or document ID
    source_metadata = Column(JSON, default=dict)  # Additional source info
    
    # Similar tickets that informed this suggestion (stored as JSON list of UUIDs)
    similar_ticket_ids = Column(JSON, default=list)
    
    # Quality scores
    relevance_score = Column(Float, nullable=True)  # 0-1
    confidence = Column(Float, nullable=True)  # 0-1
    semantic_similarity = Column(Float, nullable=True)  # Cosine similarity
    
    # Ranking
    rank = Column(Integer, default=0)  # Order in suggestions list
    
    # Feedback
    was_used = Column(Boolean, default=False)
    was_modified = Column(Boolean, default=False)
    rating = Column(Integer, nullable=True)  # 1-5 agent rating
    feedback = Column(Text, nullable=True)  # Agent feedback text
    
    # Timestamps
    created_at = Column(
        DateTime(timezone=True),
        default=datetime.utcnow,
        nullable=False
    )
    used_at = Column(DateTime(timezone=True), nullable=True)
    
    def __repr__(self) -> str:
        return f"<SuggestedResponse(id={self.id}, ticket_id={self.ticket_id}, rank={self.rank})>"


# Default response templates to seed
DEFAULT_TEMPLATES = [
    {
        "name": "Standard Greeting",
        "content": "Hello {customer_name},\n\nThank you for contacting us. I've reviewed your request and I'm happy to assist you.",
        "content_tr": "Merhaba {customer_name},\n\nBizimle iletişime geçtiğiniz için teşekkür ederiz. Talebinizi inceledim ve size yardımcı olmaktan memnuniyet duyarım.",
        "template_type": TemplateType.GREETING,
        "placeholders": ["customer_name"],
    },
    {
        "name": "Standard Closing",
        "content": "If you have any further questions, please don't hesitate to reach out.\n\nBest regards,\n{agent_name}",
        "content_tr": "Başka sorularınız olursa lütfen çekinmeden bize ulaşın.\n\nSaygılarımla,\n{agent_name}",
        "template_type": TemplateType.CLOSING,
        "placeholders": ["agent_name"],
    },
    {
        "name": "Ticket Acknowledgment",
        "content": "Thank you for submitting your request. Your ticket number is #{ticket_id}.\n\nOur team will review your request and respond within {sla_hours} hours.",
        "content_tr": "Talebinizi ilettiğiniz için teşekkür ederiz. Destek numaranız: #{ticket_id}.\n\nEkibimiz talebinizi inceleyecek ve {sla_hours} saat içinde size dönüş yapacaktır.",
        "template_type": TemplateType.ACKNOWLEDGMENT,
        "placeholders": ["ticket_id", "sla_hours"],
        "categories": [],
    },
    {
        "name": "Technical Issue Acknowledgment",
        "content": "I understand you're experiencing a technical issue. I apologize for any inconvenience this has caused.\n\nLet me investigate this for you. Could you please provide:\n1. The exact error message you're seeing\n2. Steps to reproduce the issue\n3. Your browser/device information",
        "content_tr": "Teknik bir sorun yaşadığınızı anlıyorum. Bu durumun size verdiği rahatsızlık için özür dilerim.\n\nBu sorunu sizin için araştırmama izin verin. Lütfen aşağıdaki bilgileri paylaşır mısınız:\n1. Gördüğünüz tam hata mesajı\n2. Sorunu yeniden oluşturma adımları\n3. Tarayıcı/cihaz bilgileriniz",
        "template_type": TemplateType.ACKNOWLEDGMENT,
        "categories": ["technical_issue", "bug_report"],
    },
    {
        "name": "Billing Inquiry Response",
        "content": "Thank you for reaching out about your billing inquiry.\n\nI've reviewed your account and here's what I found:\n{billing_details}\n\nIf you need any clarification or have additional questions, please let me know.",
        "content_tr": "Fatura sorgulamanız için bizimle iletişime geçtiğiniz için teşekkür ederiz.\n\nHesabınızı inceledim ve şunları tespit ettim:\n{billing_details}\n\nHerhangi bir açıklamaya ihtiyacınız olursa veya ek sorularınız varsa lütfen bana bildirin.",
        "template_type": TemplateType.SOLUTION,
        "categories": ["billing_question"],
        "placeholders": ["billing_details"],
    },
    {
        "name": "Escalation Notice",
        "content": "I've escalated your case to our senior support team for further assistance. You can expect to hear from them within {escalation_sla} hours.\n\nYour escalation reference is: {escalation_id}",
        "content_tr": "Durumunuzu daha fazla yardım için üst düzey destek ekibimize ilettim. {escalation_sla} saat içinde sizinle iletişime geçecekler.\n\nEskasyon referans numaranız: {escalation_id}",
        "template_type": TemplateType.ESCALATION,
        "placeholders": ["escalation_sla", "escalation_id"],
    },
    {
        "name": "Feature Request Acknowledgment",
        "content": "Thank you for sharing your feature suggestion! We appreciate customers who take the time to help us improve.\n\nI've logged your request (#{ticket_id}) and forwarded it to our product team for consideration. While I can't promise a timeline, your feedback is valuable and will be reviewed.\n\nIs there anything else I can help you with today?",
        "content_tr": "Özellik önerinizi paylaştığınız için teşekkür ederiz! Ürünümüzü geliştirmemize yardımcı olmak için zaman ayıran müşterilerimize minnettarız.\n\nTalebinizi (#{ticket_id}) kaydettim ve değerlendirme için ürün ekibimize ilettim. Bir zaman çizelgesi vaat edemesem de geri bildiriminiz değerli ve incelenecektir.\n\nBugün size yardımcı olabileceğim başka bir konu var mı?",
        "template_type": TemplateType.ACKNOWLEDGMENT,
        "categories": ["feature_request"],
        "placeholders": ["ticket_id"],
    },
    {
        "name": "Refund Processed",
        "content": "Good news! Your refund request has been processed.\n\nRefund amount: {refund_amount}\nRefund method: {refund_method}\nExpected arrival: {refund_eta}\n\nPlease note that it may take {processing_days} business days for the refund to appear in your account.",
        "content_tr": "İyi haber! İade talebiniz işleme alındı.\n\nİade tutarı: {refund_amount}\nİade yöntemi: {refund_method}\nTahmini varış: {refund_eta}\n\nİadenin hesabınıza yansıması {processing_days} iş günü sürebilir.",
        "template_type": TemplateType.SOLUTION,
        "categories": ["return_refund"],
        "placeholders": ["refund_amount", "refund_method", "refund_eta", "processing_days"],
    },
]
